#!/sbin/sh
#

#
# Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
#

. /lib/svc/share/smf_include.sh

# SMF_FMRI is the name of the target service. This allows multiple instances
# to use the same script.

getproparg() {
	val=`svcprop -p $1 $SMF_FMRI`
	[ -n "$val" ] && echo $val
}

MYSQLBIN=`getproparg mysql/bin`
MYSQLDATA=`getproparg mysql/data`
PIDFILE=${MYSQLDATA}/`/usr/bin/uname -n`.pid

if [ -z $SMF_FMRI ]; then
	echo "SMF framework variables are not initialized."
	exit $SMF_EXIT_ERR
fi

if [ -z ${MYSQLDATA} ]; then
	echo "mysql/data property not set"
	exit $SMF_EXIT_ERR_CONFIG
fi

if [ ! -d ${MYSQLDATA} ]; then
	echo "mysql/data directory ${MYSQLDATA} is not a valid MySQL data directory"
	exit $SMF_EXIT_ERR_CONFIG
fi

if [ ! -d ${MYSQLDATA}/mysql ]; then
	${MYSQLBIN}/mysql_install_db --user=mysql --basedir=/usr/mysql/5.6 --datadir=${MYSQLDATA}
fi


mysql_start() 	{

    MYSQLDVAL=`getproparg mysql/enable_64bit mysql:version_56`
    echo "enable_64bit: ${MYSQLDVAL}"
    echo "`ls -l /usr/mysql/5.6/bin`"
    if [ "$MYSQLDVAL" != "" ] ; then
	case "$MYSQLDVAL" in
	    true|1)
		#Check if the system architecture supports 64-bit applications
		PLATFORM=`isainfo -b`
		if [ "${PLATFORM}" != "64" ]; then
		    echo "This system is not capable of supporting 64-bit applications."
		    echo "Set the \"enable_64bit\" property value to \"false\" to start the 32-bit server."
		    exit $SMF_EXIT_ERR_CONFIG
		else
		    echo ${MYSQLBIN}/64/mysqld_safe --user=mysql --basedir=/usr/mysql/5.6 --datadir=${MYSQLDATA} --pid-file=${PIDFILE} --ledir=${MYSQLBIN}/64 --plugin-dir=lib/64/plugin
		    ${MYSQLBIN}/64/mysqld_safe --user=mysql --basedir=/usr/mysql/5.6 --datadir=${MYSQLDATA} --pid-file=${PIDFILE} --ledir=${MYSQLBIN}/64 --plugin-dir=lib/64/plugin > /dev/null &
		fi
		;;
	    false|0)
		echo ${MYSQLBIN}/mysqld_safe --user=mysql --basedir=/usr/mysql/5.6 --datadir=${MYSQLDATA} --pid-file=${PIDFILE} --ledir=${MYSQLBIN} --plugin-dir=lib/plugin
		${MYSQLBIN}/mysqld_safe --user=mysql --basedir=/usr/mysql/5.6 --datadir=${MYSQLDATA} --pid-file=${PIDFILE} --ledir=${MYSQLBIN} --plugin-dir=lib/plugin > /dev/null &
		;;
	esac
    fi
    
}


mysql_stop()	{
	if [ -f ${PIDFILE} ]; then
	pkill mysqld
	fi
}

case "$1" in
'start')
	mysql_start
	;;

'stop')
	mysql_stop
	;;


*)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;

esac
exit $SMF_EXIT_OK
