#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# Copyright 2009 Andras Barna andras.barna@gmail.com


. /lib/svc/share/smf_include.sh
. /lib/svc/share/ipf_include.sh

#
#  For ipfilter method. Normal start method will 'ignore' this information.
#
port=6667
if [ "$1" = "ipfilter" ]; then
	FMRI=$2
	out=`fmri_to_file $FMRI $IPF_SUFFIX`
else
	out=`fmri_to_file $SMF_FMRI $IPF_SUFFIX`
fi

if [ ! -f /etc/ngircd.conf ]; then
	echo "Error: Configuration file '/etc/ngircd.conf' not found." \
	    " see man ngircd.conf(5)"
	exit $SMF_EXIT_ERR_CONFIG
fi

#
# Create ipfilter rules 
#
if [ -n "$1" -a "$1" = "ipfilter" ]; then
	policy=`get_policy $FMRI`

	echo "# $FMRI server rules" >>$out
	tport=6667
	if [ -n "$tport" ]; then
		generate_rules $FMRI $policy "tcp" "any" $tport $out
	fi

	exit $SMF_EXIT_OK
fi

/usr/sbin/ngircd -f /etc/ngircd.conf
