#!/bin/sh

. /lib/svc/share/smf_include.sh

getproparg() {
        val=`svcprop -p $1 $SMF_FMRI`
        [ -n "$val" ] && echo $val
}

JETTY_JAVA=`getproparg jetty/java`
JETTY_HOMEDIR=`getproparg jetty/jetty_home`
JETTY_EXEC_USER=`getproparg jetty/exec_user`
PIDFILE='/var/run/jetty/jetty.pid'


if [ -z $SMF_FMRI ]; then
	echo "Error: SMF framework variables are not initialized"
	exit $SMF_EXIT_ERR
fi

case "$1" in
'start')
	printf "Starting jetty:"
	if [ ! -d `dirname ${PIDFILE}` ]
	then
	    mkdir -p `dirname ${PIDFILE}`
	fi
	cd ${JETTY_HOMEDIR}
	sudo -u ${JETTY_EXEC_USER} ${JETTY_JAVA} -jar start.jar &
	echo $! > ${PIDFILE}
        ;;
'stop')
    if [ -f $PIDFILE ]
    then
	printf "Stopping jetty:"
	kill `cat ${PIDFILE}`
	rm ${PIDFILE}
    else
	printf "pid file not found: ${PIDFILE}"
    fi
    ;;
*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;

esac
exit $SMF_EXIT_OK
