#!/bin/sh

. /lib/svc/share/smf_include.sh

getproparg() {
        val=`svcprop -p $1 $SMF_FMRI`
        [ -n "$val" ] && echo $val
}

ES_BIN=`getproparg elasticsearch/bin`
ES_HOMEDIR=`getproparg elasticsearch/homedir`
ES_DATADIR=`getproparg elasticsearch/datadir`
ES_LOGDIR=`getproparg elasticsearch/logdir`
ES_CONFIG=`getproparg elasticsearch/config`
ES_HEAPSIZE=`getproparg elasticsearch/heapsize`
PIDFILE='/var/elasticsearch/elasticsearch.pid'


if [ -z $SMF_FMRI ]; then
	echo "Error: SMF framework variables are not initialized"
	exit $SMF_EXIT_ERR
fi

case "$1" in
'start')
	printf "Starting Elasticsearch:"
	ES_HEAP_SIZE=${ES_HEAPSIZE} ${ES_BIN} \
	    -d \
	    -p ${PIDFILE} \
            -p ${PIDFILE} \
	    -Des.path.conf=${ES_CONFIG} \
	    -Des.path.home=${ES_HOMEDIR} \
	    -Des.path.logs=${ES_LOGDIR} \
	    -Des.path.data=${ES_DATADIR}
        ;;
'stop')
    if [ -f $PIDFILE ]
    then
	printf "Stopping elasticsearch:"
	kill `cat ${PIDFILE}`
    else
	printf "pid file not found: ${PIDFILE}"
    fi
    ;;
*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;

esac
exit $SMF_EXIT_OK
