#! /bin/sh
#
# chkconfig: - 85 15
# description: zabbix agent daemon
#

### BEGIN INIT INFO
# Provides: zabbix-agent
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start:
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: start and stop zabbix agent
# Description: Zabbix Agent
### END INIT INFO

# zabbix details
ZABBIX_AGENTD=/usr/sbin/zabbix_agentd
CONF=/etc/zabbix/1.8/zabbix_agentd.conf
PIDFILE=/var/zabbix/1.8/run/zabbix_agentd.pid

# Source function library.
#. /etc/rc.d/init.d/functions

# Source networking configuration.
#. /etc/sysconfig/network

# Check that networking is up.
#[ ${NETWORKING} = "no" ] && exit 0

[ -x $ZABBIX_AGENTD ] || exit 5
if [ ! -e $CONF ]; then
    echo "Error in file $CONF." 1>&2
    exit 6
fi

RETVAL=0

case "$1" in
    start)
        echo "Starting zabbix agent: \c"
        $ZABBIX_AGENTD -c $CONF
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/zabbix/1.8/run/zabbix-agent
        ;;
    stop)
        echo "Shutting down zabbix agent: \c"
        pkill -9 -n zabbix_agentd
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/zabbix/1.8/run/zabbix-agent
        ;;
    restart|reload)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
    condrestart)
        if [ -f /var/zabbix/1.8/run/zabbix-agent ]; then
            $0 stop
            $0 start
        fi
        RETVAL=$?
        ;;
    *)
	echo "Usage: $0 {start|stop|restart|condrestart|reload}"
	exit 1
	;;
esac

exit $RETVAL

